FROM debian:jessie
ENV RETHINKDB_PACKAGE_VERSION 2.3.6~0jessie
WORKDIR /data
RUN apt-key adv --keyserver keys.gnupg.net --recv-keys 3B87619DF812A63A8C1005C30742918E5C8DA04A \
    && echo "deb http://download.rethinkdb.com/apt jessie main" > /etc/apt/sources.list.d/rethinkdb.list \
    && apt-get update \
	&& apt-get install --no-install-recommends -y rethinkdb=$RETHINKDB_PACKAGE_VERSION \
	&& rm -rf /var/lib/apt/lists/*
VOLUME ["/data"]
CMD ["rethinkdb", "--bind", "all"]