version: '3'
networks:
  gopherDigest:
services:
  app:
    networks:
    - gopherDigest
    container_name: GopherDigest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "/usr/bin/mysql:/usr/bin/mysql"
      - "/usr/bin/vendor_perl:/usr/bin/vendor_perl"
    environment:
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=localhost
      - MYSQL_PORT=${MYSQL_PORT}
    depends_on:
      - mysql
    restart: always
  mysql:
    networks:
    - gopherDigest
    container_name: MySQL
    image: mysql:8.0
    volumes:
      - "./data:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=employees
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST=${MYSQL_HOST}