version: '3'
networks:
  gopherDigest:
services:
  app:
    networks:
    - gopherDigest
    container_name: GopherDigest
    build: .
    volumes:
      - "/usr/bin/mysql:/usr/bin/mysql"
      - "/usr/bin/vendor_perl/pt-query-digest:/usr/bin/vendor_perl/pt-query-digest"
    environment:
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
    links:
      - mysql
  mysql:
    networks:
    - gopherDigest
    container_name: MySQL
    image: mysql:latest
    volumes:
      - "/usr/bin/mysql:/usr/bin/mysql"
      - "/var/lib/mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}