version: '3'
networks:
  gopherDigest:
services:
  app:
    networks:
    - gopherDigest
    container_name: GopherDigest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "/usr/bin/mysql:/usr/bin/mysql"
      - "/var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock"
      - "/usr/bin/pt-query-digest:/usr/bin/pt-query-digest"
    env_file:
      - ./Docker/mysql.env
    depends_on:
      - mysql
      - rethinkdb
    restart: always
  mysql:
    networks:
    - gopherDigest
    container_name: MySQL
    image: mysql:8.0
    volumes:
      - "./data:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
    env_file:
      - ./Docker/mysql.env
  rethinkdb:
    networks:
    - gopherDigest
    container_name: RethinkDB
    build:
      context: .
      dockerfile: Dockerfile-RethinkDB
    env_file:
      - ./Docker/rethinkdb.env
    ports:
      - "28015:28015"
      - "29015:29015"
      - "8080:8080"