version: '3'
networks:
  gopherDigest:
services:
  app:
    networks:
    - gopherDigest
    container_name: GopherDigest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "/usr/bin/mysql:/usr/bin/mysql"
      - "/usr/bin/pt-query-digest:/usr/bin/pt-query-digest"
    env_file:
      - ./Docker/mysql.env
    depends_on:
      - mysql
    restart: always
  mysql:
    networks:
    - gopherDigest
    container_name: MySQL
    image: mysql:8.0
    volumes:
      - "./data:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
    env_file:
      - ./Docker/mysql.env

      
